[workspace]
resolver = "2"
members = ["utracker_launcher"]
default-members = ["utracker_launcher"]

[workspace.package]
edition = "2021"
authors = ["Ruttie"]
version = "0.1.1"
rust-version = "1.81.0"
license = "ISC"
readme = "README.md"
repository = "https://github.com/Ruttie2006/UTracker-Launcher"